server:
  port: 8081
spring:
  application:
    name: item-service
  datasource:
    url: jdbc:mysql://localhost:3306/yun6 #不用配驱动，可以推断
    username: root
    password: GUOJIE123
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
#    instance:
#      prefer-ip-address: true
#      ip-adress: 127.0.0.1